# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\eric\IS620\motor.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(549, 497)
        Form.setMinimumSize(QtCore.QSize(20, 20))
        Form.setFocusPolicy(QtCore.Qt.NoFocus)
        Form.setAcceptDrops(True)
        self.cb_com = QtWidgets.QComboBox(Form)
        self.cb_com.setGeometry(QtCore.QRect(210, 110, 80, 25))
        self.cb_com.setObjectName("cb_com")
        self.cb_bund = QtWidgets.QComboBox(Form)
        self.cb_bund.setGeometry(QtCore.QRect(210, 80, 80, 25))
        self.cb_bund.setObjectName("cb_bund")
        self.bt_max = QtWidgets.QPushButton(Form)
        self.bt_max.setGeometry(QtCore.QRect(340, 270, 140, 50))
        self.bt_max.setObjectName("bt_max")
        self.bt_min = QtWidgets.QPushButton(Form)
        self.bt_min.setGeometry(QtCore.QRect(140, 270, 140, 50))
        self.bt_min.setObjectName("bt_min")
        self.le_speed = QtWidgets.QLineEdit(Form)
        self.le_speed.setGeometry(QtCore.QRect(140, 360, 140, 50))
        self.le_speed.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("DigifaceWide")
        font.setPointSize(18)
        self.le_speed.setFont(font)
        self.le_speed.setMaxLength(3276)
        self.le_speed.setDragEnabled(False)
        self.le_speed.setObjectName("le_speed")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 320, 70, 16))
        self.label_2.setObjectName("label_2")
        self.bt_opencom = QtWidgets.QPushButton(Form)
        self.bt_opencom.setGeometry(QtCore.QRect(340, 77, 140, 61))
        self.bt_opencom.setObjectName("bt_opencom")
        self.ln_speed = QtWidgets.QLCDNumber(Form)
        self.ln_speed.setGeometry(QtCore.QRect(340, 180, 140, 50))
        self.ln_speed.setProperty("intValue", 101)
        self.ln_speed.setObjectName("ln_speed")
        self.bt_setspeed = QtWidgets.QPushButton(Form)
        self.bt_setspeed.setEnabled(True)
        self.bt_setspeed.setGeometry(QtCore.QRect(340, 360, 140, 50))
        self.bt_setspeed.setObjectName("bt_setspeed")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 90, 70, 12))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(140, 120, 70, 12))
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(20, 150, 500, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(140, 200, 100, 12))
        self.label_4.setObjectName("label_4")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(119, 330, 401, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(20, 240, 500, 20))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(110, 60, 20, 371))
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 70, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 100, 70, 16))
        self.label_6.setObjectName("label_6")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(20, 50, 500, 16))
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(20, 420, 500, 16))
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(130, 10, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(100, 440, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.bt_max.setText(_translate("Form", "max_speed 3000"))
        self.bt_min.setText(_translate("Form", "min_speed 20"))
        self.le_speed.setText(_translate("Form", "500"))
        self.label_2.setText(_translate("Form", "速度设置"))
        self.bt_opencom.setText(_translate("Form", "打开串口"))
        self.bt_setspeed.setText(_translate("Form", "设置速度"))
        self.bt_setspeed.setShortcut(_translate("Form", "Enter"))
        self.label.setText(_translate("Form", "端口号："))
        self.label_3.setText(_translate("Form", "波特率："))
        self.label_4.setText(_translate("Form", "速度显示值："))
        self.label_5.setText(_translate("Form", "速度显示"))
        self.label_6.setText(_translate("Form", "通讯设置"))
        self.label_7.setText(_translate("Form", "电机控制程序（IS620P）"))
        self.label_8.setText(_translate("Form", "公司：长沙南车电气设备有限公司  作者：redmorningcn"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
